n1 = input('digite algo para ver suas informações ')
print ('é alfa numerico?', n1.isalnum())
print ("é alfa?", n1.isalpha())
print ('é numero?', n1.isnumeric())
print ("é decimal?",n1.isdecimal())
print ('é um dígito?', n1.isdigit())
print ('é um indentificador?', n1.isidentifier())
print ('é tudo minúsculo?', n1.islower())
print ('é imprimível?', n1.isprintable())
print ('é um espaço?', n1.isspace())
print ('é um tituo?', n1.istitle())
print ('é tudo maiúsculo?', n1.isupper())
print (type(n1))

